In [2]:
import cv2
import numpy as np

In [ ]:
grayscale_image = cv2.imread('images/download.jfif', cv2.IMREAD_GRAYSCALE)
rgb_image = cv2.cvtColor(grayscale_image, cv2.COLOR_GRAY2RGB)
rgb_image[:, :, 0] = 0
rgb_image[:, :, 1] = 3
rgb_image[:, :, 1] = 4

bgr_image_for_display = cv2.cvtColor(rgb_image, cv2.COLOR_RGB2BGR)
cv2.imshow('Grayscale image', grayscale_image)
cv2.imshow('Blue-Tinted 24-bit RGB Image', bgr_image_for_display)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Enhance Image - Convert from BGR to HSV

In [ ]:
# Convert from BGR to HSV
hsv_image = cv2.cvtColor(bgr_image_for_display, cv2.COLOR_BGR2HSV)

### 1. Modify HSV image's Hue

In [ ]:
# Get hue shift value from the user
hue_shift = int(input('Enter the hue shift value (0-179): '))

# Modify the hue channel
hue_channel = hsv_image[:, :, 0]
hue_channel = (hue_channel + hue_shift) % 180
hsv_image[:, :, 0] = hue_channel


### 2. Modify HSV image's Saturation

In [ ]:
# Ask the user for the saturation effect with the use input
multiplier = float(input("Enter the stauration multiplier (e.g. 1.5): "))

# Effect of saturation
saturation_channel = hsv_image[:, :, 1]

# Apply the saturation effect with the user input
saturation_channel = np.clip(saturation_channel * multiplier, 0, 255)

hsv_image[:, :, 1] = saturation_channel

### 3. Modify HSV Image's Value

In [ ]:
# Get user imput for the value adjustment
value_adjustment = int(input('Enter the value adjustment amount: '))

# Effect of value
value_channel = hsv_image[:, :, 2]
value_channel = np.clip(value_channel +  value_adjustment, a_min=0, a_max=255)
hsv_image[:, :, 2] = value_channel

In [ ]:
# Convert back to BGR
modified_image = cv2.cvtColor(hsv_image, cv2.COLOR_HSV2BGR)

# Display the images
cv2.imshow('OG Image', bgr_image_for_display)
cv2.imshow('Modified Image', modified_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## TV Regularization - Denoise Images

In [ ]:
import cv2
from skimage.restoration import denoise_tv_chambolle
noised_img = cv2.imread('images/noised_image.jpg', cv2.IMREAD_GRAYSCALE)

lambda_reg = 0.2
denoised_img = denoise_tv_chambolle(noised_img, weight = lambda_reg)
cv2.imshow('OG image', noised_img)
cv2.imshow('Denoised image', denoised_img)

cv2.waitKey(0)
cv2.destroyAllWindows()


## RLE Compression

In [34]:
import cv2
import numpy as np
def rle_compression(image):
    """Compresses image data using RLE compression algorithm"""
    encoded_img= []
    counter = 1

    for i in image[1:]:
        if (image[i] == image[i-1]):
            counter += 1
        else:
            encoded_img.extend([counter, image[i]])
            counter = 1
    encoded_img.extend([counter, image[i]])
    return encoded_img


image = np.ones((30,30), dtype=np.uint8)*255

cv2.imshow('OG Gray Image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

pixels = image.flatten()

compressed_data = rle_compression(pixels)

np.save('compressed_img', compressed_data)
print('OG Image Size', len(image))
print('Compressed Image Size: ',  len(compressed_data))

OG Image Size 30
Compressed Image Size:  2


## Draw a Straight Line

In [37]:
import cv2
import numpy as np

# Create a blank white image
image = np.ones((500, 500, 3),dtype=np.uint8) * 255

# Define the starting and ending coordinates of the line
start_point = (300, 10) # Starting coordinates
end_point = (10, 400) # Ending coordinates

# Define the color (Red in BGR format) and thickness of the line
color = (0, 0, 255) # Red color in BGR
thickness = 5 # Thickness of the line

# Draw the line on the image
cv2.line(image, start_point, end_point, color, thickness)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## Draw Reversed Line

In [38]:
import cv2
cv2.line(image, (10,10), (300,400), (100, 0, 0), thickness)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## Draw a Circle

In [39]:
center = (150, 200)
cv2.circle(image, center, 50, (100, 0, 0), 1)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## Draw a Rectangle

In [40]:
cv2.rectangle(image, start_point, end_point, color, thickness)
cv2.imshow('Final Image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Rotate an Image - cv2.getRotationMatrix2D()

In [43]:
# Define the center of rotation, angle, and scale
rotation_center = (image.shape[1] // 2, image.shape[0] // 2)

angle = 90 # Rotation angle in degrees
scale = 0.1 # Scale factor

rotation_matrix = cv2.getRotationMatrix2D(rotation_center, angle, scale)

rotated_img = cv2.warpAffine(image, rotation_matrix, dsize=(image.shape[1], image.shape[0]))

cv2.imshow('Rotated Image', rotated_img)
cv2.waitKey(0)
cv2.destroyAllWindows()